### ISSUE TITLE
Guggy not Working on My RocketChat

### ISSUE THREAD

**Issue by mehdiyahyaoui** [thorstenspringhart/GuggyRocketChat#3]
Hello 

Sorry for not reporting back on the issues 

My Problems is still the same - the integration not working

Here's what it shows on the log

```

 [34mI20170315-08:57:03.010(1) rocketchat_integrations rocketchat_integrations.js:854 [31mIntegrations ➔ Outgoing WebHook.error Error running Script in the Integration Guggy: 
[34mI20170315-08:57:03.013(1) rocketchat_integrations rocketchat_integrations.js:857 [31mIntegrations ➔ Outgoing WebHook.error Stack: 
[34mI20170315-08:57:03.014(1) rocketchat_integrations rocketchat_integrations.js:858 [31mIntegrations ➔ Outgoing WebHook.error   TypeError: Cannot read property 'gif' of undefined       at Script.process_outgoing_response (script.js:1:1188)       at evalmachine.<anonymous>:1:15       at ContextifyScript.Script.runInNewContext (vm.js:18:15)       at Object.exports.runInNewContext (vm.js:49:17)       at /snap/rocketchat-server/528/programs/server/packages/rocketchat_integrations.js:835:29       at RocketChatIntegrationHandler.executeScript (/snap/rocketchat-server/528/programs/server/packages/rocketchat_integrations.js:844:6)       at /snap/rocketchat-server/528/programs/server/packages/rocketchat_integrations.js:1462:32       at runWithEnvironment (packages/meteor.js:1176:24) 
[34mI20170315-08:57:03.017(1) rocketchat_integrations rocketchat_integrations.js:1496 [31mIntegrations ➔ Outgoing WebHook.error Error for the Integration "Guggy" to http://text2gif.guggy.com/guggify is: 
[34mI20170315-08:57:03.019(1) rocketchat_integrations rocketchat_integrations.js:1497 [31mIntegrations ➔ Outgoing WebHook.error { [Error: getaddrinfo EAI_AGAIN text2gif.guggy.com:80]   code: 'EAI_AGAIN',   errno: 'EAI_AGAIN',   syscall: 'getaddrinfo',   hostname: 'text2gif.guggy.com',   host: 'text2gif.guggy.com',   port: 80 }

below the version of my RC instance
```

![image](https://cloud.githubusercontent.com/assets/23338414/23938896/88692386-095e-11e7-90d7-be3c5adf4ca9.png)

```
```

**Comment by rabidang3ls** [comment]
I just installed the guggy integration and it works fine for me.

![screenshot 2017-08-08 16 47 11](https://user-images.githubusercontent.com/2701664/29097934-dc2ba8fe-7c59-11e7-8795-90d4bddf5492.png)

**Comment by thorstenspringhart** [comment]
Is your server able to connect to text2gif.guggy.com? The "EAI_AGAIN" error actually means a failure in dns name resolution
